---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/mthirion/code-red-breach-challenge-hacker-app
    app.quarkus.io/quarkus-version: 3.27.2.redhat-00001
    app.quarkus.io/commit-id: 9eedb0fa99148e66b932e55272d18353f8deffd0
    app.quarkus.io/vcs-uri: https://github.com/mthirion/code-red-breach-challenge-hacker-app.git
    app.quarkus.io/build-timestamp: 2026-03-26 - 08:15:48 +0000
  labels:
    app.kubernetes.io/name: hackerapp
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: hackerapp
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: hackerapp
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: hackerapp
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: openjdk-17
spec:
  dockerImageRepository: registry.access.redhat.com/ubi9/openjdk-17
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/mthirion/code-red-breach-challenge-hacker-app
    app.quarkus.io/quarkus-version: 3.27.2.redhat-00001
    app.quarkus.io/commit-id: 9eedb0fa99148e66b932e55272d18353f8deffd0
    app.quarkus.io/vcs-uri: https://github.com/mthirion/code-red-breach-challenge-hacker-app.git
    app.quarkus.io/build-timestamp: 2026-03-26 - 08:15:48 +0000
  labels:
    app.kubernetes.io/name: hackerapp
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: hackerapp
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/mthirion/code-red-breach-challenge-hacker-app
    app.quarkus.io/quarkus-version: 3.27.2.redhat-00001
    app.quarkus.io/commit-id: 9eedb0fa99148e66b932e55272d18353f8deffd0
    app.quarkus.io/vcs-uri: https://github.com/mthirion/code-red-breach-challenge-hacker-app.git
    app.quarkus.io/build-timestamp: 2026-03-26 - 08:15:48 +0000
  labels:
    app.kubernetes.io/name: hackerapp
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: hackerapp
spec:
  output:
    to:
      kind: ImageStreamTag
      name: hackerapp:1.0-SNAPSHOT
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-17:1.23
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/mthirion/code-red-breach-challenge-hacker-app
    app.quarkus.io/quarkus-version: 3.27.2.redhat-00001
    app.quarkus.io/commit-id: 9eedb0fa99148e66b932e55272d18353f8deffd0
    app.quarkus.io/vcs-uri: https://github.com/mthirion/code-red-breach-challenge-hacker-app.git
    app.quarkus.io/build-timestamp: 2026-03-26 - 08:15:48 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/name: hackerapp
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: hackerapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hackerapp
      app.kubernetes.io/version: 1.0-SNAPSHOT
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
        app.openshift.io/vcs-uri: https://github.com/mthirion/code-red-breach-challenge-hacker-app
        app.quarkus.io/quarkus-version: 3.27.2.redhat-00001
        app.quarkus.io/commit-id: 9eedb0fa99148e66b932e55272d18353f8deffd0
        app.quarkus.io/vcs-uri: https://github.com/mthirion/code-red-breach-challenge-hacker-app.git
        app.quarkus.io/build-timestamp: 2026-03-26 - 08:15:48 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/name: hackerapp
        app.kubernetes.io/version: 1.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: hackerapp:1.0-SNAPSHOT
          imagePullPolicy: Always
          name: hackerapp
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/mthirion/code-red-breach-challenge-hacker-app
    app.quarkus.io/quarkus-version: 3.27.2.redhat-00001
    app.quarkus.io/commit-id: 9eedb0fa99148e66b932e55272d18353f8deffd0
    app.quarkus.io/vcs-uri: https://github.com/mthirion/code-red-breach-challenge-hacker-app.git
    app.quarkus.io/build-timestamp: 2026-03-26 - 08:15:48 +0000
  labels:
    app.kubernetes.io/name: hackerapp
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: hackerapp
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: hackerapp
