%dev.quarkus.http.port=8092
quarkus.http.port=8080
quarkus.smallrye-openapi.store-schema-directory=./

api.key=4f9d2a1b-7e8c-4a3b-9d2f-1a2b3c4d5e6f

quarkus.kubernetes-client.connection-timeout=60000
quarkus.kubernetes-client.request-timeout=60000

quarkus.ui.always-include=false
quarkus.vertx.access-log.enabled=false
quarkus.http.non-application-root.path=/disabled

# Disable SmallRye Health (Liveness/Readiness)
quarkus.health.extensions.enabled=false

# Disable Metrics (Prometheus)
quarkus.metrics.enabled=false

# Disable OpenAPI/Swagger
quarkus.openapi-ui.enabled=false